# Server configuration
server.port=${PORT:3000}

# NFC configuration mapping from environment variables
nfc.master-key-hex=${MASTER_KEY_HEX:00000000000000000000000000000000}
nfc.reader-name=${CL_READER:ACS ACR1252 Dual Reader PICC}

# Logging configuration
logging.level.com.example.nfc=DEBUG
logging.level.org.springframework.web=INFO

# Database configuration mapping from env variables
spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3306/your_database_name}
spring.datasource.username=${DB_USERNAME:your_db_username}
spring.datasource.password=${DB_PASSWORD:your_db_password}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA configurations
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

